<html>
<head>
    <title>Rick y Morty App</title>
    <?php $this->assets->outputCss(); ?>
</head>
<body>
    <nav>
        <div class="nav-wrapper">
            <ul id="nav-mobile" class="left hide-on-med-and-down">
                <li><a href="/episode">Capítulos</a></li>
                <li><a href="/character">Personajes</a></li>
            </ul>
        </div>
    </nav>

    <div class="content">

        <h1>Bienvenido a la página</h1>

    </div>

    <?php $this->assets->outputJs(); ?>
</body>
</html>